// Code generated by error-generator v1.0.0; DO NOT EDIT.
// Source: errors/codes.go
// Manifest: ef60d053e3c4be75

package incident

import "errors"

// ErrorCode is a stable, machine-readable application error code carried in the
// "code" field of an APIError. Compare against the generated constants below
// instead of matching human-readable messages.
//
// The values mirror github.com/grafana/incident/pkg/errors and are generated
// from the same source, so this client can be a separate module without
// importing the server.
type ErrorCode string

const (
	// ErrInternalError is the "common.internal_error" error code: Internal Server Error.
	ErrInternalError ErrorCode = "common.internal_error"
	// ErrUnauthorized is the "common.unauthorized" error code: Unauthorized.
	ErrUnauthorized ErrorCode = "common.unauthorized"
	// ErrForbidden is the "common.forbidden" error code: Forbidden.
	ErrForbidden ErrorCode = "common.forbidden"
	// ErrNotFound is the "common.not_found" error code: Not Found.
	ErrNotFound ErrorCode = "common.not_found"
	// ErrValidationFailed is the "common.validation_failed" error code: Validation Failed.
	ErrValidationFailed ErrorCode = "common.validation_failed"
	// ErrRateLimited is the "common.rate_limited" error code: Rate Limited.
	ErrRateLimited ErrorCode = "common.rate_limited"
	// ErrConflict is the "common.conflict" error code: Conflict.
	ErrConflict ErrorCode = "common.conflict"
	// ErrFeatureDisabled is the "common.feature_disabled" error code: Feature Disabled.
	ErrFeatureDisabled ErrorCode = "common.feature_disabled"
	// ErrIncidentNotFound is the "incidents.not_found" error code: Incident Not Found.
	ErrIncidentNotFound ErrorCode = "incidents.not_found"
	// ErrIncidentAlreadyClosed is the "incidents.already_closed" error code: Incident Already Closed.
	ErrIncidentAlreadyClosed ErrorCode = "incidents.already_closed"
	// ErrIncidentInvalidStatusTransition is the "incidents.invalid_status_transition" error code: Invalid Status Transition.
	ErrIncidentInvalidStatusTransition ErrorCode = "incidents.invalid_status_transition"
	// ErrIncidentCreationFailed is the "incidents.creation_failed" error code: Incident Creation Failed.
	ErrIncidentCreationFailed ErrorCode = "incidents.creation_failed"
	// ErrIntegrationNotFound is the "integrations.not_found" error code: Integration Not Found.
	ErrIntegrationNotFound ErrorCode = "integrations.not_found"
	// ErrIntegrationNotConfigured is the "integrations.not_configured" error code: Integration Not Configured.
	ErrIntegrationNotConfigured ErrorCode = "integrations.not_configured"
	// ErrSlackIntegrationError is the "integrations.slack_error" error code: Slack Integration Error.
	ErrSlackIntegrationError ErrorCode = "integrations.slack_error"
	// ErrWebhookFailed is the "integrations.webhook_failed" error code: Webhook Failed.
	ErrWebhookFailed ErrorCode = "integrations.webhook_failed"
	// ErrTaskNotFound is the "tasks.not_found" error code: Task Not Found.
	ErrTaskNotFound ErrorCode = "tasks.not_found"
	// ErrTaskAlreadyCompleted is the "tasks.already_completed" error code: Task Already Completed.
	ErrTaskAlreadyCompleted ErrorCode = "tasks.already_completed"
	// ErrRoleNotFound is the "roles.not_found" error code: Role Not Found.
	ErrRoleNotFound ErrorCode = "roles.not_found"
	// ErrRoleNameConflict is the "roles.name_conflict" error code: Role Name Conflict.
	ErrRoleNameConflict ErrorCode = "roles.name_conflict"
	// ErrRoleMaximumActiveReached is the "roles.maximum_active_reached" error code: Maximum Active Roles Reached.
	ErrRoleMaximumActiveReached ErrorCode = "roles.maximum_active_reached"
	// ErrRoleMinimumActiveRequired is the "roles.minimum_active_required" error code: Minimum Active Roles Required.
	ErrRoleMinimumActiveRequired ErrorCode = "roles.minimum_active_required"
	// ErrStatusNotFound is the "statuses.not_found" error code: Status Not Found.
	ErrStatusNotFound ErrorCode = "statuses.not_found"
	// ErrInvestigationNotFound is the "investigations.not_found" error code: Investigation Not Found.
	ErrInvestigationNotFound ErrorCode = "investigations.not_found"
	// ErrUserNotFound is the "users.not_found" error code: User Not Found.
	ErrUserNotFound ErrorCode = "users.not_found"
)

// HasErrorCode reports whether err, or any error it wraps, is an *APIError with
// the given ErrorCode.
//
//	if incident.HasErrorCode(err, incident.ErrRoleNotFound) {
//		// the role is gone; drop it from local state
//	}
func HasErrorCode(err error, code ErrorCode) bool {
	var apiErr *APIError
	if errors.As(err, &apiErr) {
		return apiErr.Code == code
	}
	return false
}
